on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
jobs:
  deploy-env:
    runs-on: ubuntu-latest

    environment: ${{inputs.environment}}
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Entorno seleccionado
        run: echo "El environment seleccionado $environment"

      - name: Set environment variables
        run: |
          echo "API_URL=${{ env.API_URL }}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${{ env.LOG_LEVEL }}" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
          echo "API_URL: ${{ secrets.API_URL }}"
          echo "LOG_LEVEL: ${{ secrets.LOG_LEVEL }}"

      - name: Deploy application
        run: |
          echo "Starting deployment to ${{ inputs.environment }}..."

